import 'package:flutter/material.dart';
import 'core.dart';
import 'branded_store.dart';
import 'wallet.dart';

class BrandedSignupPage extends StatefulWidget {
  const BrandedSignupPage({super.key});
  @override State<BrandedSignupPage> createState()=>_BrandedSignupPageState();
}
class _BrandedSignupPageState extends State<BrandedSignupPage>{
  final name=TextEditingController(),phone=TextEditingController(); bool terms=false;
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:brandRed,body:SafeArea(child:ListView(padding:const EdgeInsets.all(24),children:[
    const SizedBox(height:18),Center(child:Container(width:120,height:120,padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(30)),child:ClipRRect(borderRadius:BorderRadius.circular(22),child:Image.asset('Ativos/Marca/zecapao_app_icon.png',fit:BoxFit.cover)))),
    const SizedBox(height:26),const Text('O Capão chegou.',style:TextStyle(color:Colors.white,fontSize:34,fontWeight:FontWeight.w900)),const Text('Tudo que Vale, entregue até você.',style:TextStyle(color:Colors.white70,fontSize:15)),const SizedBox(height:22),
    Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:appBg,borderRadius:BorderRadius.circular(26)),child:Column(children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Seu nome',prefixIcon:Icon(Icons.person_outline_rounded))),const SizedBox(height:12),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'WhatsApp',prefixIcon:Icon(Icons.phone_outlined))),CheckboxListTile(contentPadding:EdgeInsets.zero,value:terms,activeColor:brandRed,onChanged:(v)=>setState(()=>terms=v??false),title:const Text('Aceito os termos e a política de privacidade',style:TextStyle(fontSize:12))),FilledButton(onPressed:terms?()=>Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>BrandedHomePage(customerName:name.text.trim().isEmpty?'Capão':name.text.trim(),phone:phone.text.trim()))):null,child:const SizedBox(width:double.infinity,child:Text('ENTRAR NO ZÉ CAPÃO',textAlign:TextAlign.center)))]))
  ])));
}

class BrandedHomePage extends StatefulWidget{
  final String customerName,phone; const BrandedHomePage({super.key,required this.customerName,required this.phone});
  @override State<BrandedHomePage> createState()=>_BrandedHomePageState();
}
class _BrandedHomePageState extends State<BrandedHomePage>{
  final repo=Repo(),search=TextEditingController(); late Future<List<Store>> storesFuture; late Future<List<CampaignBanner>> bannersFuture; late Future<ValeCoinBalance> walletFuture; int tab=0;
  @override void initState(){super.initState();storesFuture=repo.stores();bannersFuture=repo.banners();walletFuture=repo.valecoinBalance(widget.phone);}
  @override void dispose(){search.dispose();super.dispose();}
  Future<void> refreshAll()async{final s=repo.stores(),b=repo.banners(),w=repo.valecoinBalance(widget.phone);setState((){storesFuture=s;bannersFuture=b;walletFuture=w;});await Future.wait([s,b,w]);}
  Future<void> openStore(Store s)async{if(!s.isOpen)return;await Navigator.push(context,MaterialPageRoute(builder:(_)=>BrandedStorePage(store:s,customerName:widget.customerName,phone:widget.phone,repo:repo)));if(mounted)setState(()=>walletFuture=repo.valecoinBalance(widget.phone));}
  Widget logo(Store s,{double size=54}){Widget f=Image.asset(s.localLogo,width:size,height:size,fit:BoxFit.contain,errorBuilder:(_,__,___)=>const Icon(Icons.storefront_rounded,color:brandRed));return s.logoUrl.isEmpty?f:Image.network(s.logoUrl,width:size,height:size,fit:BoxFit.contain,errorBuilder:(_,__,___)=>f);}

  Widget header()=>Row(children:[Container(width:46,height:46,padding:const EdgeInsets.all(3),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(15)),child:ClipRRect(borderRadius:BorderRadius.circular(12),child:Image.asset('Ativos/Marca/zecapao_app_icon.png',fit:BoxFit.cover))),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Salve, ${widget.customerName}!',style:const TextStyle(fontSize:12,color:brandMuted,fontWeight:FontWeight.w600)),const Row(children:[Icon(Icons.location_on_rounded,size:16,color:brandRed),SizedBox(width:2),Text('Vale do Capão • BA',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900))])])),Container(width:42,height:42,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.notifications_none_rounded))]);

  Widget banners(List<Store> stores)=>FutureBuilder<List<CampaignBanner>>(future:bannersFuture,builder:(_,snap){final list=snap.data??[];if(list.isEmpty)return const SizedBox.shrink();return SizedBox(height:186,child:PageView.builder(controller:PageController(viewportFraction:.93),itemCount:list.length,itemBuilder:(_,i){final b=list[i],fg=hexColor(b.textHex,Colors.white),bg=hexColor(b.backgroundHex,brandRed);return Padding(padding:const EdgeInsets.only(right:10),child:InkWell(borderRadius:BorderRadius.circular(28),onTap:(){if(b.targetType=='store'){final f=stores.where((s)=>s.id==b.targetValue).toList();if(f.isNotEmpty)openStore(f.first);}else if(b.title.toLowerCase().contains('valecoin')){Navigator.push(context,MaterialPageRoute(builder:(_)=>ValeCoinWalletPage(phone:widget.phone,repo:repo)));}},child:Container(clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:bg,borderRadius:BorderRadius.circular(28)),child:Stack(fit:StackFit.expand,children:[if(b.imageUrl.isNotEmpty)Image.network(b.imageUrl,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const SizedBox.shrink()),if(b.imageUrl.isNotEmpty)Container(color:Colors.black.withValues(alpha:.34)),Padding(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text(b.title,maxLines:2,style:TextStyle(color:fg,fontSize:27,fontWeight:FontWeight.w900,height:1.03)),if(b.subtitle.isNotEmpty)...[const SizedBox(height:7),SizedBox(width:270,child:Text(b.subtitle,maxLines:2,overflow:TextOverflow.ellipsis,style:TextStyle(color:fg.withValues(alpha:.88),fontSize:12.5)))],if(b.ctaLabel.isNotEmpty)...[const SizedBox(height:13),Container(padding:const EdgeInsets.symmetric(horizontal:13,vertical:7),decoration:BoxDecoration(color:brandYellow,borderRadius:BorderRadius.circular(13)),child:Text(b.ctaLabel,style:const TextStyle(color:brandInk,fontSize:9,fontWeight:FontWeight.w900)))]]))]))));}));});

  Widget categories(){const items=[('Comer & Beber',Icons.restaurant_rounded,brandRed),('Mercados',Icons.shopping_cart_outlined,brandGreen),('Lojas',Icons.shopping_bag_outlined,Color(0xFFF2994A)),('Hospedagem',Icons.bed_outlined,Color(0xFF9B51E0)),('Experiências',Icons.landscape_outlined,Color(0xFF299E91)),('Serviços',Icons.work_outline_rounded,Color(0xFF2F80ED)),('Eventos',Icons.local_activity_outlined,Color(0xFFEB4D8B))];return SizedBox(height:105,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:items.length,separatorBuilder:(_,__)=>const SizedBox(width:10),itemBuilder:(_,i){final x=items[i];return InkWell(onTap:()=>setState(()=>tab=x.$1=='Eventos'?3:1),borderRadius:BorderRadius.circular(20),child:SizedBox(width:76,child:Column(children:[Container(width:62,height:62,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),boxShadow:const [BoxShadow(color:Color(0x0B000000),blurRadius:14,offset:Offset(0,5))]),child:Icon(x.$2,color:x.$3,size:28)),const SizedBox(height:7),Text(x.$1,maxLines:2,textAlign:TextAlign.center,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:10,fontWeight:FontWeight.w700,height:1.05))]))); }));}

  Widget walletHero()=>FutureBuilder<ValeCoinBalance>(future:walletFuture,builder:(_,snap){final w=snap.data??ValeCoinBalance.zero();return InkWell(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ValeCoinWalletPage(phone:widget.phone,repo:repo))),borderRadius:BorderRadius.circular(26),child:Container(padding:const EdgeInsets.all(19),decoration:BoxDecoration(gradient:const LinearGradient(colors:[brandNavy,brandInk],begin:Alignment.topLeft,end:Alignment.bottomRight),borderRadius:BorderRadius.circular(26)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:52,height:52,alignment:Alignment.center,decoration:const BoxDecoration(color:brandYellow,shape:BoxShape.circle),child:const Text('V',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900,color:brandInk))),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('MEU VALECOIN',style:TextStyle(color:Colors.white70,fontSize:10,fontWeight:FontWeight.w900,letterSpacing:1)),Text('${w.balanceCoins} VC',style:const TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.w900)),Text('${valecoinMoney(w.balanceCoins)} em benefícios',style:const TextStyle(color:Colors.white60,fontSize:11))])),const Icon(Icons.chevron_right_rounded,color:Colors.white70)]),const SizedBox(height:14),Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:9),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.08),borderRadius:BorderRadius.circular(14)),child:const Row(children:[Icon(Icons.auto_awesome_rounded,color:brandYellow,size:17),SizedBox(width:8),Expanded(child:Text('Ganhe de 1% a 3% de volta nas compras elegíveis.',style:TextStyle(color:Colors.white,fontSize:11,fontWeight:FontWeight.w600))),Text('SAIBA +',style:TextStyle(color:brandYellow,fontSize:9,fontWeight:FontWeight.w900))]))])));});

  Widget storeCard(Store s,{bool compact=false})=>InkWell(onTap:()=>openStore(s),borderRadius:BorderRadius.circular(22),child:Container(width:compact?224:null,margin:compact?EdgeInsets.zero:const EdgeInsets.only(bottom:13),clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),boxShadow:const [BoxShadow(color:Color(0x0C000000),blurRadius:17,offset:Offset(0,6))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(s.coverUrl.isNotEmpty)SizedBox(height:compact?82:110,width:double.infinity,child:Image.network(s.coverUrl,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(color:brandBeige))),Padding(padding:const EdgeInsets.all(12),child:Row(children:[Container(width:compact?48:58,height:compact?48:58,padding:const EdgeInsets.all(4),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(15),border:Border.all(color:const Color(0x11000000))),child:ClipRRect(borderRadius:BorderRadius.circular(10),child:logo(s,size:compact?42:52))),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(s.name,maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(fontSize:compact?14:16,fontWeight:FontWeight.w900)),const SizedBox(height:3),Text('${s.estimatedMinutes} min • Frete ${money(s.deliveryFee)}',style:const TextStyle(fontSize:10,color:brandMuted,fontWeight:FontWeight.w600)),const SizedBox(height:4),Row(children:[const Icon(Icons.star_rounded,size:14,color:brandYellow),const Text('4,9',style:TextStyle(fontSize:10,fontWeight:FontWeight.w800)),const Spacer(),Text(s.isOpen?'ABERTO':'FECHADO',style:TextStyle(fontSize:8.5,fontWeight:FontWeight.w900,color:s.isOpen?brandGreen:brandRed))])]))]))])));

  Widget home(List<Store> stores)=>RefreshIndicator(onRefresh:refreshAll,child:ListView(padding:const EdgeInsets.fromLTRB(16,10,16,28),children:[header(),const SizedBox(height:15),GestureDetector(onTap:()=>setState(()=>tab=1),child:const AbsorbPointer(child:TextField(decoration:InputDecoration(hintText:'Buscar produtos, lojas, serviços...',prefixIcon:Icon(Icons.search_rounded))))),const SizedBox(height:16),banners(stores),const SizedBox(height:22),const Text('O que você precisa hoje?',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:10),categories(),const SizedBox(height:10),walletHero(),const SizedBox(height:25),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Destaques no Vale',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text('${stores.length} parceiros',style:const TextStyle(color:brandRed,fontSize:11,fontWeight:FontWeight.w800))]),const SizedBox(height:10),SizedBox(height:150,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:stores.length,separatorBuilder:(_,__)=>const SizedBox(width:11),itemBuilder:(_,i)=>storeCard(stores[i],compact:true))),const SizedBox(height:25),const Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('Parceiros do Capão',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text('Ver todos',style:TextStyle(color:brandRed,fontSize:11,fontWeight:FontWeight.w800))]),const SizedBox(height:10),...stores.map(storeCard),const SizedBox(height:8),Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:brandInk,borderRadius:BorderRadius.circular(24)),child:const Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Explore o Vale',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900)),SizedBox(height:5),Text('Hospedagem, trilhas, eventos, cultura e serviços locais.',style:TextStyle(color:Colors.white70,fontSize:11,height:1.4))])),CircleAvatar(radius:25,backgroundColor:brandYellow,child:Icon(Icons.landscape_rounded,color:brandInk))]))]));

  Widget searchPage(List<Store> stores){final q=search.text.trim().toLowerCase(),f=q.isEmpty?stores:stores.where((s)=>s.name.toLowerCase().contains(q)||s.description.toLowerCase().contains(q)).toList();return ListView(padding:const EdgeInsets.all(16),children:[const Text('Buscar no Vale',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:13),TextField(controller:search,autofocus:true,onChanged:(_)=>setState((){}),decoration:InputDecoration(hintText:'Café, pizza, mercado...',prefixIcon:const Icon(Icons.search_rounded),suffixIcon:search.text.isEmpty?null:IconButton(onPressed:(){search.clear();setState((){});},icon:const Icon(Icons.close_rounded)))),const SizedBox(height:18),...f.map(storeCard)]);}
  Widget orders()=>_empty('Meus pedidos','Acompanhe pedidos em andamento e reveja suas compras.',Icons.receipt_long_rounded);
  Widget events()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Eventos no Vale',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:7),const Text('Agenda, cultura e experiências do Capão.',style:TextStyle(color:brandMuted)),const SizedBox(height:20),Container(height:178,padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[brandRed,brandNavy],begin:Alignment.topLeft,end:Alignment.bottomRight),borderRadius:BorderRadius.circular(26)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.end,children:[Text('CAPÃO REGGAE VALE',style:TextStyle(color:brandYellow,fontSize:10,fontWeight:FontWeight.w900,letterSpacing:1)),SizedBox(height:5),Text('Música, encontro e Chapada.',style:TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),Text('Descubra a agenda do Vale.',style:TextStyle(color:Colors.white70,fontSize:12))]))]);
  Widget account()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Minha conta',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:16),walletHero(),const SizedBox(height:16),...[(Icons.location_on_outlined,'Meus endereços'),(Icons.confirmation_number_outlined,'Cupons'),(Icons.credit_card_outlined,'Pagamentos'),(Icons.help_outline_rounded,'Ajuda')].map((x)=>Container(margin:const EdgeInsets.only(bottom:9),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:ListTile(leading:Icon(x.$1,color:brandRed),title:Text(x.$2,style:const TextStyle(fontWeight:FontWeight.w700)),trailing:const Icon(Icons.chevron_right_rounded))))]);
  Widget _empty(String title,String text,IconData icon)=>ListView(padding:const EdgeInsets.all(16),children:[Text(title,style:const TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:20),Container(padding:const EdgeInsets.all(26),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24)),child:Column(children:[CircleAvatar(radius:32,backgroundColor:brandBeige,child:Icon(icon,color:brandRed,size:31)),const SizedBox(height:13),Text(text,textAlign:TextAlign.center,style:const TextStyle(color:brandMuted))]))]);

  @override Widget build(BuildContext context)=>FutureBuilder<List<Store>>(future:storesFuture,builder:(_,snap){if(snap.connectionState==ConnectionState.waiting)return const Scaffold(body:Center(child:CircularProgressIndicator()));if(snap.hasError)return Scaffold(body:SafeArea(child:_empty('Zé Capão','Não foi possível carregar os parceiros. Puxe para atualizar.',Icons.cloud_off_rounded)));final stores=snap.data??[];final pages=[home(stores),searchPage(stores),orders(),events(),account()];return Scaffold(backgroundColor:appBg,body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home_rounded),label:'Início'),NavigationDestination(icon:Icon(Icons.search_rounded),label:'Buscar'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),label:'Pedidos'),NavigationDestination(icon:Icon(Icons.local_activity_outlined),label:'Eventos'),NavigationDestination(icon:Icon(Icons.person_outline_rounded),label:'Conta')]));});
}
