import 'package:flutter/material.dart';
import 'core.dart';
import 'branded_store.dart';
import 'category_hub.dart';

class ShowcaseHomePage extends StatefulWidget {
  final String customerName;
  final String phone;
  const ShowcaseHomePage({super.key, required this.customerName, required this.phone});
  @override State<ShowcaseHomePage> createState()=>_ShowcaseHomePageState();
}
class _ShowcaseHomePageState extends State<ShowcaseHomePage>{
 final repo=Repo(); late Future<List<Store>> storesFuture; int tab=0;
 @override void initState(){super.initState();storesFuture=repo.stores();}
 Future<void> openStore(Store s)async{if(!s.isOpen)return;await Navigator.push(context,MaterialPageRoute(builder:(_)=>BrandedStorePage(store:s,customerName:widget.customerName,phone:widget.phone,repo:repo)));}
 Future<void> openCategory(String c)async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>CategoryHubPage(category:c,customerName:widget.customerName,phone:widget.phone,repo:repo)));}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:appBg,bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.home_rounded),label:'Início'),NavigationDestination(icon:Icon(Icons.search_rounded),label:'Buscar'),NavigationDestination(icon:Icon(Icons.receipt_long_rounded),label:'Pedidos'),NavigationDestination(icon:Icon(Icons.explore_outlined),label:'Explorar'),NavigationDestination(icon:Icon(Icons.person_outline_rounded),label:'Conta')]),body:SafeArea(child:FutureBuilder<List<Store>>(future:storesFuture,builder:(_,snap){final stores=snap.data??<Store>[];if(tab!=0)return _simpleTab(tab);return RefreshIndicator(onRefresh:()async=>setState(()=>storesFuture=repo.stores()),child:ListView(padding:const EdgeInsets.fromLTRB(17,12,17,28),children:[_header(),const SizedBox(height:18),Container(height:58,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(19)),child:const Row(children:[SizedBox(width:18),Icon(Icons.search_rounded,size:28),SizedBox(width:14),Expanded(child:Text('O que você procura no Vale?',style:TextStyle(color:brandMuted,fontSize:16)))])),const SizedBox(height:22),const Text('Tudo por aqui',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:12),_categories(),const SizedBox(height:22),const Text('Parceiros em destaque',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:11),_partners(stores),const SizedBox(height:26),const Text('Mais do que delivery',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:12),Row(children:[Expanded(child:_explore('Hospedagens',Icons.hotel_rounded,()=>openCategory('Hospedagem'))),const SizedBox(width:10),Expanded(child:_explore('Experiências',Icons.hiking_rounded,()=>openCategory('Experiências'))),const SizedBox(width:10),Expanded(child:_explore('Eventos',Icons.local_activity_rounded,()=>openCategory('Eventos')))])]));})));
 Widget _header()=>Row(children:[Container(width:51,height:51,padding:const EdgeInsets.all(3),decoration:BoxDecoration(color:brandRed,borderRadius:BorderRadius.circular(17)),child:ClipRRect(borderRadius:BorderRadius.circular(14),child:Image.asset('Ativos/Marca/zecapao_app_icon.png',fit:BoxFit.cover))),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Salve, ${widget.customerName}!',style:const TextStyle(fontSize:11,color:brandMuted,fontWeight:FontWeight.w700)),const SizedBox(height:2),const Row(children:[Icon(Icons.location_on_rounded,color:brandRed,size:17),SizedBox(width:3),Text('Vale do Capão • BA',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900))])])),Container(width:45,height:45,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.notifications_none_rounded))]);
 Widget _categories(){const items=[('Comida',Icons.lunch_dining_rounded),('Café',Icons.coffee_rounded),('Pizza',Icons.local_pizza_rounded),('Mercado',Icons.shopping_basket_rounded),('Hospedagem',Icons.hotel_rounded),('Experiências',Icons.hiking_rounded),('Eventos',Icons.local_activity_rounded)];return SizedBox(height:108,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:items.length,separatorBuilder:(_,__)=>const SizedBox(width:10),itemBuilder:(_,i){final x=items[i];return InkWell(onTap:()=>openCategory(x.$1),child:SizedBox(width:74,child:Column(children:[Container(width:68,height:68,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Icon(x.$2,color:brandRed,size:32)),const SizedBox(height:7),Text(x.$1,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:10,fontWeight:FontWeight.w800))]))); }));}
 Widget _partners(List<Store> stores){if(stores.isEmpty)return const SizedBox(height:110,child:Center(child:Text('Parceiros em atualização',style:TextStyle(color:brandMuted))));return SizedBox(height:142,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:stores.length,separatorBuilder:(_,__)=>const SizedBox(width:10),itemBuilder:(_,i){final s=stores[i];return InkWell(onTap:()=>openStore(s),child:Container(width:128,padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22)),child:Column(children:[ClipRRect(borderRadius:BorderRadius.circular(16),child:SizedBox(width:76,height:76,child:s.logoUrl.isNotEmpty?Image.network(s.logoUrl,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Image.asset(s.localLogo,fit:BoxFit.cover)):Image.asset(s.localLogo,fit:BoxFit.cover))),const SizedBox(height:8),Text(s.name,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w900))]))); }));}
 Widget _explore(String label,IconData icon,VoidCallback tap)=>InkWell(onTap:tap,child:Container(height:100,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,color:brandRed,size:31),const SizedBox(height:8),Text(label,textAlign:TextAlign.center,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w900))])));
 Widget _simpleTab(int i){const t=['Início','Buscar','Pedidos','Explorar','Conta'];return Center(child:Text(t[i],style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900)));}
}
