import { createClient } from '@supabase/supabase-js'

const supabase=createClient('https://yovjbqtazkreruvxoawf.supabase.co','sb_publishable_qOQlqYHbhc1005WoMOZS6g__52vXAor')
const app=document.querySelector('#app')
let enhancing=false
const slugify=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
function toast(msg,err=false){let n=document.querySelector('#cat-toast');if(!n){n=document.createElement('div');n.id='cat-toast';n.style.cssText='position:fixed;right:22px;bottom:22px;z-index:9999;padding:12px 16px;border-radius:12px;color:#fff;font:700 13px system-ui;box-shadow:0 12px 40px #0003';document.body.appendChild(n)}n.style.background=err?'#b3261e':'#238b57';n.textContent=msg;n.style.display='block';setTimeout(()=>n.style.display='none',2200)}
async function getCats(){const{data,error}=await supabase.from('categories').select('*').order('sort_order');if(error){toast(error.message,true);return[]}return data||[]}
async function saveCat(id,payload){const{error}=await supabase.from('categories').update(payload).eq('id',id);if(error){toast(error.message,true);return false}toast('Categoria atualizada ✓');return true}
async function swap(cat,dir,cats){const idx=cats.findIndex(x=>x.id===cat.id),j=idx+dir;if(j<0||j>=cats.length)return;const other=cats[j],a=cat.sort_order,b=other.sort_order;const r=await Promise.all([supabase.from('categories').update({sort_order:b}).eq('id',cat.id),supabase.from('categories').update({sort_order:a}).eq('id',other.id)]);if(r.some(x=>x.error))return toast('Não foi possível reordenar.',true);toast('Ordem atualizada ✓');location.reload()}
function newCategoryModal(cats){const wrap=document.createElement('div');wrap.className='cat-modal';wrap.innerHTML=`<div class="cat-modal-card"><h2>Nova categoria</h2><p>Crie uma nova categoria para a Home.</p><label>Nome<input id="cat-new-name" placeholder="Ex.: Artesanato"></label><label>Subtítulo<input id="cat-new-sub" placeholder="Opcional"></label><div class="cat-colors"><label>Cor de fundo<input id="cat-new-bg" type="color" value="#F6E8D8"></label><label>Cor de destaque<input id="cat-new-accent" type="color" value="#E72E27"></label></div><div class="cat-modal-actions"><button id="cat-cancel">Cancelar</button><button id="cat-create" class="cat-primary">Criar categoria</button></div></div>`;document.body.appendChild(wrap);wrap.querySelector('#cat-cancel').onclick=()=>wrap.remove();wrap.querySelector('#cat-create').onclick=async()=>{const name=wrap.querySelector('#cat-new-name').value.trim();if(!name)return toast('Digite o nome da categoria.',true);const slugBase=slugify(name)||'categoria',existing=new Set(cats.map(x=>x.slug));let slug=slugBase,n=2;while(existing.has(slug))slug=`${slugBase}-${n++}`;const max=Math.max(0,...cats.map(x=>Number(x.sort_order||0)));const{error}=await supabase.from('categories').insert({name,slug,subtitle:wrap.querySelector('#cat-new-sub').value.trim(),sort_order:max+1,is_active:true,background_color:wrap.querySelector('#cat-new-bg').value,accent_color:wrap.querySelector('#cat-new-accent').value});if(error)return toast(error.message,true);toast('Nova categoria criada ✓');wrap.remove();location.reload()}}
function addStyles(){if(document.querySelector('#categories-admin-style'))return;const s=document.createElement('style');s.id='categories-admin-style';s.textContent=`.cat-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:12px 0 18px}.cat-toolbar button,.cat-primary{border:0;border-radius:12px;background:#e72e27;color:#fff;padding:11px 15px;font-weight:850;cursor:pointer}.cat-editor{margin-top:14px;padding-top:14px;border-top:1px solid #eee7df}.cat-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cat-grid label{font-size:11px;font-weight:800}.cat-grid input{margin-top:5px}.cat-pos{display:flex;gap:6px;align-items:center}.cat-pos input{width:76px}.cat-pos button{border:1px solid #ddd6cc;background:#fff;border-radius:9px;padding:8px 10px;cursor:pointer}.cat-actions{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:12px}.cat-actions button{border:0;border-radius:10px;padding:9px 12px;font-weight:800;cursor:pointer}.cat-save{background:#242330;color:#fff}.cat-toggle{background:#eef7f1;color:#16733d}.cat-toggle.off{background:#f5eeee;color:#a22}.cat-modal{position:fixed;inset:0;z-index:9998;background:#0007;display:grid;place-items:center;padding:20px}.cat-modal-card{width:min(480px,100%);background:#fff;border-radius:22px;padding:24px;display:grid;gap:13px}.cat-modal-card h2{margin:0}.cat-modal-card label{font-size:12px;font-weight:800}.cat-modal-card input{width:100%;margin-top:6px}.cat-colors{display:grid;grid-template-columns:1fr 1fr;gap:12px}.cat-modal-actions{display:flex;justify-content:flex-end;gap:8px}.cat-modal-actions button{border:0;padding:11px 14px;border-radius:10px;font-weight:800;cursor:pointer}.cat-modal-actions button:first-child{background:#eee9e1}.cat-card-inactive{opacity:.58}.cat-color-row{display:flex;gap:8px}.cat-color-row input[type=color]{height:42px;padding:3px}@media(max-width:700px){.cat-grid,.cat-colors{grid-template-columns:1fr}.cat-toolbar{align-items:stretch;flex-direction:column}.cat-toolbar button{width:100%}}`;document.head.appendChild(s)}
async function enhance(){if(enhancing)return;const heading=[...document.querySelectorAll('.panel h2')].find(h=>h.textContent.trim()==='Categorias');if(!heading)return;const panel=heading.closest('.panel'),grid=heading.parentElement.querySelector('.product-grid');if(!grid||grid.dataset.catEnhanced==='1')return;enhancing=true;addStyles();const cats=await getCats();if(!cats.length&&grid.children.length===0){enhancing=false;return}grid.dataset.catEnhanced='1';const toolbar=document.createElement('div');toolbar.className='cat-toolbar';toolbar.innerHTML=`<div><b>Personalize as categorias</b><div style="font-size:12px;color:#77747a;margin-top:3px">Crie, renomeie, reordene, troque cores, ícones e disponibilidade.</div></div><button id="cat-new">＋ Nova categoria</button>`;grid.parentNode.insertBefore(toolbar,grid);toolbar.querySelector('#cat-new').onclick=()=>newCategoryModal(cats);
 const cards=[...grid.children];cards.forEach(card=>{const input=card.querySelector('input[data-upload][data-table="categories"]');if(!input)return;const id=input.dataset.id,cat=cats.find(x=>String(x.id)===String(id));if(!cat)return;if(!cat.is_active)card.classList.add('cat-card-inactive');const box=document.createElement('div');box.className='cat-editor';box.innerHTML=`<div class="cat-grid"><label>Nome<input data-cat="name" value="${esc(cat.name)}"></label><label>Slug<input data-cat="slug" value="${esc(cat.slug)}"></label><label>Subtítulo<input data-cat="subtitle" value="${esc(cat.subtitle||'')}"></label><label>Posição<div class="cat-pos"><button data-move="-1" title="Subir">↑</button><input data-cat="sort_order" type="number" min="1" value="${Number(cat.sort_order||0)}"><button data-move="1" title="Descer">↓</button></div></label><label>Cor de fundo<div class="cat-color-row"><input data-cat="background_color" type="color" value="${esc(cat.background_color||'#F6E8D8')}"></div></label><label>Cor de destaque<div class="cat-color-row"><input data-cat="accent_color" type="color" value="${esc(cat.accent_color||'#E72E27')}"></div></label></div><div class="cat-actions"><button class="cat-toggle ${cat.is_active?'':'off'}">${cat.is_active?'Ativa':'Desativada'}</button><button class="cat-save">Salvar categoria</button></div>`;card.appendChild(box);box.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>swap(cat,Number(b.dataset.move),cats));box.querySelector('.cat-toggle').onclick=async()=>{if(await saveCat(id,{is_active:!cat.is_active}))location.reload()};box.querySelector('.cat-save').onclick=async()=>{const payload={};box.querySelectorAll('[data-cat]').forEach(el=>payload[el.dataset.cat]=el.type==='number'?Number(el.value):el.value.trim());if(!payload.name)return toast('Nome obrigatório.',true);payload.slug=slugify(payload.slug||payload.name);if(await saveCat(id,payload))location.reload()}});enhancing=false}
const observer=new MutationObserver(()=>setTimeout(enhance,20));observer.observe(app,{childList:true,subtree:true});setTimeout(enhance,100)
