import { createClient } from '@supabase/supabase-js'
import './styles.css'

const supabase = createClient('https://yovjbqtazkreruvxoawf.supabase.co','sb_publishable_qOQlqYHbhc1005WoMOZS6g__52vXAor')
const state={session:null,admin:false,tab:'dashboard',data:{}}
const app=document.querySelector('#app')
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const money=v=>`R$ ${Number(v||0).toFixed(2).replace('.',',')}`
async function isAdmin(s){if(!s?.user?.id)return false;const{data,error}=await supabase.from('profiles').select('role').eq('id',s.user.id).maybeSingle();return !error&&data?.role==='admin'}
async function loadAll(){const q=await Promise.all([supabase.from('app_entry_config').select('*').order('sort_order'),supabase.from('home_sections').select('*').order('sort_order'),supabase.from('stores').select('*').order('name'),supabase.from('products').select('*').order('sort_order'),supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(30),supabase.from('events').select('*').order('starts_at',{ascending:true}),supabase.from('campaign_banners').select('*').order('sort_order')]);['entry','home','stores','products','orders','events','banners'].forEach((k,i)=>state.data[k]=q[i].data||[])}
function loginView(message='',ok=false){app.innerHTML=`<main class="login"><section class="login-card"><div class="brand-mark">ZÉ<br><b>CAPÃO</b></div><p class="eyebrow">ADMIN v0.3</p><h1>O painel que controla o Vale.</h1><p class="muted">Acesso restrito à administração do Zé Capão.</p><form id="loginForm"><label>E-mail<input name="email" type="email" required></label><label>Senha<input name="password" type="password" required></label>${message?`<div class="${ok?'success':'error'}">${esc(message)}</div>`:''}<button>ENTRAR</button><button type="button" id="forgotPassword" class="text-button">Esqueci minha senha</button></form></section></main>`;document.querySelector('#forgotPassword').onclick=()=>forgotView();document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),{data,error}=await supabase.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)return loginView('E-mail ou senha inválidos.');if(!(await isAdmin(data.session))){await supabase.auth.signOut();return loginView('Esta conta não possui permissão administrativa.')}await boot(data.session)}}
function forgotView(message='',ok=false){app.innerHTML=`<main class="login"><section class="login-card"><div class="brand-mark">ZÉ<br><b>CAPÃO</b></div><p class="eyebrow">RECUPERAÇÃO</p><h1>Recuperar senha</h1><form id="forgotForm"><label>E-mail<input name="email" type="email" required value="carlosright@gmail.com"></label>${message?`<div class="${ok?'success':'error'}">${esc(message)}</div>`:''}<button>ENVIAR LINK</button><button type="button" id="backLogin" class="text-button">Voltar</button></form></section></main>`;document.querySelector('#backLogin').onclick=()=>loginView();document.querySelector('#forgotForm').onsubmit=async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email'),{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:'https://zecapao-admin.vercel.app/'});forgotView(error?error.message:'Link enviado.',!error)}}
function newPasswordView(){loginView('Use o link de recuperação para definir a nova senha.',true)}
const menu=[['dashboard','Dashboard','◫'],['entry','Tela de Entrada','◉'],['home','Home','⌂'],['stores','Parceiros','◆'],['products','Produtos','▦'],['orders','Pedidos','≡'],['events','Eventos','★'],['media','Mídias','▣']]
function shell(content){app.innerHTML=`<div class="layout"><aside><div class="logo">Zé Capão <span>ADMIN</span></div><nav>${menu.map(([id,l,i])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}"><i>${i}</i>${l}</button>`).join('')}</nav><button id="logout" class="logout">Sair</button></aside><main><header><div><p class="eyebrow">ZÉ CAPÃO ADMIN</p><h1>${menu.find(x=>x[0]===state.tab)?.[1]||''}</h1></div><div class="status">● online</div></header>${content}</main></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelector('#logout').onclick=()=>supabase.auth.signOut()}
function dashboard(){const d=state.data;return `<section class="grid stats"><article><span>Parceiros</span><b>${d.stores.length}</b></article><article><span>Produtos</span><b>${d.products.length}</b></article><article><span>Pedidos recentes</span><b>${d.orders.length}</b></article><article><span>Eventos</span><b>${d.events.length}</b></article></section><section class="panel"><h2>Central editorial</h2><p class="muted">Conteúdo dinâmico do aplicativo.</p></section>`}
function entry(){return `<section class="panel"><h2>Tela de Entrada</h2><p class="muted">Mídia de abertura recomendada: <b>1080 × 1920 px</b> (9:16) · JPG/PNG/WebP.</p></section>`}
function bannerCard(x){const img=x.image_url||x.media_url||x.banner_url||'';return `<article class="editor-card banner-editor"><div class="row"><div><b>${esc(x.title||'Banner')}</b><small>Banner Home · recomendado 1200 × 600 px · proporção 2:1 · JPG/PNG/WebP</small></div><label class="switch"><input type="checkbox" data-banner-field="is_active" data-id="${x.id}" ${x.is_active?'checked':''}><span></span></label></div><div class="banner-workspace"><div class="banner-preview">${img?`<img src="${esc(img)}" alt="Prévia">`:`<div class="preview-empty"><b>PRÉVIA 2:1</b><small>1200 × 600 px</small></div>`}</div><div class="form-grid"><label>Título<input data-banner-field="title" data-id="${x.id}" value="${esc(x.title)}"></label><label>Subtítulo<input data-banner-field="subtitle" data-id="${x.id}" value="${esc(x.subtitle||'')}"></label><label>Texto do botão<input data-banner-field="cta_label" data-id="${x.id}" value="${esc(x.cta_label||'')}"></label><label>Tipo de destino<input data-banner-field="target_type" data-id="${x.id}" value="${esc(x.target_type||'')}"></label><label class="wide">URL / imagem <span class="field-help">1200 × 600 px recomendado</span><input data-banner-field="image_url" data-id="${x.id}" value="${esc(img)}" placeholder="https://..."></label><label>Destino / ID<input data-banner-field="target_id" data-id="${x.id}" value="${esc(x.target_id||x.target_value||'')}"></label><label>Ordem<input type="number" data-banner-field="sort_order" data-id="${x.id}" value="${Number(x.sort_order||0)}"></label></div></div><div class="row banner-actions"><small class="muted">A peça será exibida em recorte 2:1. Mantenha textos importantes longe das bordas.</small><button class="save" data-save-banner="${x.id}">Salvar banner</button></div></article>`}
function home(){return `<section class="panel"><div class="panel-head"><div><h2>Seções da Home</h2><p class="muted">Ordem e visibilidade do app.</p></div></div><div class="list">${state.data.home.map(x=>`<article class="list-row"><div class="order">${x.sort_order}</div><div class="grow"><b>${esc(x.title)}</b><small>${esc(x.section_type)}</small></div><label class="switch"><input type="checkbox" data-home-active="${x.id}" ${x.is_active?'checked':''}><span></span></label></article>`).join('')}</div><div class="panel-head space"><div><h2>Banners da Home</h2><p class="muted"><b>Formato recomendado: 1200 × 600 px</b> · proporção 2:1 · JPG, PNG ou WebP. O preview abaixo simula o recorte do app.</p></div></div>${state.data.banners.map(bannerCard).join('')}</section>`}
function stores(){return `<section class="panel"><h2>Parceiros</h2><p class="muted">Logo recomendada: <b>800 × 800 px</b> · 1:1. Capa: <b>1200 × 675 px</b> · 16:9.</p></section>`}function products(){return `<section class="panel"><h2>Produtos</h2><p class="muted">Foto recomendada: <b>1000 × 1000 px</b> · 1:1.</p></section>`}function orders(){return `<section class="panel"><h2>Pedidos recentes</h2></section>`}function events(){return `<section class="panel"><h2>Eventos</h2><p class="muted">Capa recomendada: <b>1200 × 675 px</b> · 16:9.</p></section>`}function media(){return `<section class="panel"><h2>Biblioteca de Mídia</h2><p class="muted">Bucket: <b>zecapao-media</b>.</p></section>`}
async function bindActions(){document.querySelectorAll('[data-home-active]').forEach(el=>el.onchange=async()=>{await supabase.from('home_sections').update({is_active:el.checked,updated_at:new Date().toISOString()}).eq('id',el.dataset.homeActive);await refresh()});document.querySelectorAll('[data-save-banner]').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.saveBanner,els=[...document.querySelectorAll(`[data-banner-field][data-id="${id}"]`)],payload={updated_at:new Date().toISOString()};els.forEach(f=>{let v=f.type==='checkbox'?f.checked:f.type==='number'?Number(f.value):f.value;if(f.dataset.bannerField==='image_url'&&!('image_url' in (state.data.banners.find(x=>String(x.id)===String(id))||{})))return;payload[f.dataset.bannerField]=v});const{error}=await supabase.from('campaign_banners').update(payload).eq('id',id);btn.textContent=error?'Erro ao salvar':'Salvo ✓';if(!error)setTimeout(refresh,700)})}
async function refresh(){await loadAll();render()}function render(){if(!state.session||!state.admin)return loginView();const views={dashboard,entry,home,stores,products,orders,events,media};shell((views[state.tab]||dashboard)());bindActions()}async function boot(s){state.session=s;state.admin=await isAdmin(s);if(!state.admin){if(s)await supabase.auth.signOut();return loginView('Acesso administrativo necessário.')}await loadAll();render()}
supabase.auth.onAuthStateChange(async(event,session)=>{if(event==='PASSWORD_RECOVERY')return newPasswordView();if(event==='SIGNED_OUT'){state.session=null;state.admin=false;return loginView()}if(session&&event!=='INITIAL_SESSION')await boot(session)});const{data:{session}}=await supabase.auth.getSession();if(session)await boot(session);else loginView()
