import { createClient } from '@supabase/supabase-js'
import './styles.css'

const supabase=createClient('https://yovjbqtazkreruvxoawf.supabase.co','sb_publishable_qOQlqYHbhc1005WoMOZS6g__52vXAor')
const state={session:null,admin:false,tab:'dashboard',data:{}}
const app=document.querySelector('#app')
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const money=v=>`R$ ${Number(v||0).toFixed(2).replace('.',',')}`
const slug=s=>String(s||'arquivo').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9.]+/g,'-').replace(/^-+|-+$/g,'')

async function isAdmin(s){if(!s?.user?.id)return false;const{data,error}=await supabase.from('profiles').select('role').eq('id',s.user.id).maybeSingle();return !error&&data?.role==='admin'}
async function loadAll(){const q=await Promise.all([supabase.from('app_entry_config').select('*').order('sort_order'),supabase.from('home_sections').select('*').order('sort_order'),supabase.from('stores').select('*').order('name'),supabase.from('products').select('*').order('sort_order'),supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(30),supabase.from('events').select('*').order('starts_at',{ascending:true}),supabase.from('campaign_banners').select('*').order('sort_order')]);['entry','home','stores','products','orders','events','banners'].forEach((k,i)=>state.data[k]=q[i].data||[])}
function notify(msg,type='ok'){let n=document.querySelector('.toast');if(!n){n=document.createElement('div');n.className='toast';document.body.appendChild(n)}n.className=`toast ${type}`;n.textContent=msg;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2600)}

function loginView(message='',ok=false){app.innerHTML=`<main class="login"><section class="login-card"><div class="brand-mark">ZÉ<br><b>CAPÃO</b></div><p class="eyebrow">ADMIN v0.4</p><h1>O painel que controla o Vale.</h1><p class="muted">Acesso restrito à administração do Zé Capão.</p><form id="loginForm"><label>E-mail<input name="email" type="email" required></label><label>Senha<input name="password" type="password" required></label>${message?`<div class="${ok?'success':'error'}">${esc(message)}</div>`:''}<button>ENTRAR</button><button type="button" id="forgotPassword" class="text-button">Esqueci minha senha</button></form></section></main>`;document.querySelector('#forgotPassword').onclick=()=>forgotView();document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),{data,error}=await supabase.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)return loginView('E-mail ou senha inválidos.');if(!(await isAdmin(data.session))){await supabase.auth.signOut();return loginView('Esta conta não possui permissão administrativa.')}await boot(data.session)}}
function forgotView(message='',ok=false){app.innerHTML=`<main class="login"><section class="login-card"><div class="brand-mark">ZÉ<br><b>CAPÃO</b></div><p class="eyebrow">RECUPERAÇÃO</p><h1>Recuperar senha</h1><form id="forgotForm"><label>E-mail<input name="email" type="email" required value="carlosright@gmail.com"></label>${message?`<div class="${ok?'success':'error'}">${esc(message)}</div>`:''}<button>ENVIAR LINK</button><button type="button" id="backLogin" class="text-button">Voltar</button></form></section></main>`;document.querySelector('#backLogin').onclick=()=>loginView();document.querySelector('#forgotForm').onsubmit=async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email'),{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:'https://zecapao-admin.vercel.app/'});forgotView(error?error.message:'Link enviado.',!error)}}
const menu=[['dashboard','Dashboard','◫'],['entry','Tela de Entrada','◉'],['home','Home','⌂'],['stores','Parceiros','◆'],['products','Produtos','▦'],['orders','Pedidos','≡'],['events','Eventos','★'],['media','Mídias','▣']]
function shell(content){app.innerHTML=`<div class="layout"><aside><div class="logo">Zé Capão <span>ADMIN</span></div><nav>${menu.map(([id,l,i])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}"><i>${i}</i>${l}</button>`).join('')}</nav><button id="logout" class="logout">Sair</button></aside><main><header><div><p class="eyebrow">ZÉ CAPÃO ADMIN</p><h1>${menu.find(x=>x[0]===state.tab)?.[1]||''}</h1></div><div class="status">● online</div></header>${content}</main></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelector('#logout').onclick=()=>supabase.auth.signOut()}
function dashboard(){const d=state.data;return `<section class="grid stats"><article><span>Parceiros</span><b>${d.stores.length}</b></article><article><span>Produtos</span><b>${d.products.length}</b></article><article><span>Pedidos recentes</span><b>${d.orders.length}</b></article><article><span>Eventos</span><b>${d.events.length}</b></article></section><section class="panel"><h2>Central editorial</h2><p class="muted">Agora o Admin também envia imagens e vídeos direto para o Supabase Storage.</p></section>`}
function preview(url,ratio='2/1',video=false){return `<div class="media-preview" style="aspect-ratio:${ratio}">${url?(video?`<video src="${esc(url)}" controls></video>`:`<img src="${esc(url)}" alt="Prévia">`):`<div class="preview-empty"><b>SEM MÍDIA</b><small>Faça upload abaixo</small></div>`}</div>`}
function uploadBox({table='',id='',field='',folder='',accept='image/*',label='Adicionar mídia',spec='',standalone=false}){return `<div class="upload-box"><div><b>${label}</b><small>${spec}</small></div><label class="upload-button">＋ Escolher arquivo<input hidden type="file" accept="${accept}" data-upload data-table="${table}" data-id="${id}" data-field="${field}" data-folder="${folder}" ${standalone?'data-standalone="1"':''}></label><div class="upload-progress" data-progress="${table}-${id}-${field}"></div></div>`}
function entry(){return `<section class="panel"><div class="panel-head"><div><h2>Tela de Entrada</h2><p class="muted"><b>1080 × 1920 px</b> · 9:16 · JPG/PNG/WebP ou vídeo MP4/WebM.</p></div></div>${state.data.entry.map(x=>{const isVideo=x.media_type==='video'||/\.(mp4|webm)(\?|$)/i.test(x.media_url||'');return `<article class="editor-card"><div class="row"><div><b>${esc(x.name)}</b><small>${esc(x.mode)}</small></div><label class="switch"><input type="checkbox" data-auto table="app_entry_config" data-id="${x.id}" data-field="is_active" ${x.is_active?'checked':''}><span></span></label></div><div class="entry-workspace">${preview(x.media_url,'9/16',isVideo)}<div>${uploadBox({table:'app_entry_config',id:x.id,field:'media_url',folder:'entrada',accept:'image/jpeg,image/png,image/webp,video/mp4,video/webm',label:'Adicionar / substituir mídia',spec:'1080 × 1920 px · 9:16 · imagem ou vídeo'})}<div class="form-grid"><label>Modo<select data-field="mode" data-id="${x.id}" data-edit-table="app_entry_config">${['login','login_campaign','media_fullscreen','media_then_login'].map(m=>`<option ${x.mode===m?'selected':''}>${m}</option>`).join('')}</select></label><label>Duração (segundos)<input type="number" data-field="media_duration_seconds" data-id="${x.id}" data-edit-table="app_entry_config" value="${x.media_duration_seconds||5}"></label><label>Título<input data-field="title" data-id="${x.id}" data-edit-table="app_entry_config" value="${esc(x.title||'')}"></label><label>Subtítulo<input data-field="subtitle" data-id="${x.id}" data-edit-table="app_entry_config" value="${esc(x.subtitle||'')}"></label></div><button class="save" data-save-table="app_entry_config" data-id="${x.id}">Salvar Tela de Entrada</button></div></div></article>`}).join('')}</section>`}
function bannerCard(x){return `<article class="editor-card"><div class="row"><div><b>${esc(x.title||'Banner')}</b><small>1200 × 600 px · 2:1 · JPG/PNG/WebP</small></div><label class="switch"><input type="checkbox" data-auto table="campaign_banners" data-id="${x.id}" data-field="is_active" ${x.is_active?'checked':''}><span></span></label></div><div class="banner-workspace">${preview(x.image_url,'2/1') }<div>${uploadBox({table:'campaign_banners',id:x.id,field:'image_url',folder:'banners',accept:'image/jpeg,image/png,image/webp',label:'Adicionar / substituir banner',spec:'1200 × 600 px · 2:1 · até 15 MB'})}<div class="form-grid"><label>Título<input data-edit-table="campaign_banners" data-id="${x.id}" data-field="title" value="${esc(x.title)}"></label><label>Subtítulo<input data-edit-table="campaign_banners" data-id="${x.id}" data-field="subtitle" value="${esc(x.subtitle||'')}"></label><label>CTA<input data-edit-table="campaign_banners" data-id="${x.id}" data-field="cta_label" value="${esc(x.cta_label||'')}"></label><label>Destino<input data-edit-table="campaign_banners" data-id="${x.id}" data-field="target_value" value="${esc(x.target_value||'')}"></label><label>Tipo de destino<input data-edit-table="campaign_banners" data-id="${x.id}" data-field="target_type" value="${esc(x.target_type||'')}"></label><label>Ordem<input type="number" data-edit-table="campaign_banners" data-id="${x.id}" data-field="sort_order" value="${x.sort_order||0}"></label></div><button class="save" data-save-table="campaign_banners" data-id="${x.id}">Salvar banner</button></div></div></article>`}
function home(){return `<section class="panel"><h2>Seções da Home</h2><div class="list">${state.data.home.map(x=>`<article class="list-row"><div class="order">${x.sort_order}</div><div class="grow"><b>${esc(x.title)}</b><small>${esc(x.section_type)}</small></div><label class="switch"><input type="checkbox" data-auto table="home_sections" data-id="${x.id}" data-field="is_active" ${x.is_active?'checked':''}><span></span></label></article>`).join('')}</div><div class="panel-head space"><div><h2>Banners da Home</h2><p class="muted">Upload direto · <b>1200 × 600 px</b> · proporção 2:1.</p></div></div>${state.data.banners.map(bannerCard).join('')}</section>`}
function stores(){return `<section class="panel"><div class="panel-head"><div><h2>Parceiros</h2><p class="muted">Logo <b>800 × 800 px</b> · Capa <b>1200 × 675 px</b>.</p></div></div>${state.data.stores.map(x=>`<article class="editor-card"><div class="row"><div><b>${esc(x.name)}</b><small>${esc(x.slug)}</small></div><label class="switch"><input type="checkbox" data-auto table="stores" data-id="${x.id}" data-field="is_active" ${x.is_active?'checked':''}><span></span></label></div><div class="dual-media"><div><h3>Logo</h3>${preview(x.logo_url,'1/1')}${uploadBox({table:'stores',id:x.id,field:'logo_url',folder:'parceiros/logos',accept:'image/*',label:'Trocar logo',spec:'800 × 800 px · 1:1'})}</div><div><h3>Capa</h3>${preview(x.cover_url,'16/9')}${uploadBox({table:'stores',id:x.id,field:'cover_url',folder:'parceiros/capas',accept:'image/*',label:'Trocar capa',spec:'1200 × 675 px · 16:9'})}</div></div><div class="form-grid"><label>Nome<input data-edit-table="stores" data-id="${x.id}" data-field="name" value="${esc(x.name)}"></label><label>Telefone<input data-edit-table="stores" data-id="${x.id}" data-field="phone" value="${esc(x.phone||'')}"></label><label class="wide">Descrição<input data-edit-table="stores" data-id="${x.id}" data-field="description" value="${esc(x.description||'')}"></label></div><button class="save" data-save-table="stores" data-id="${x.id}">Salvar parceiro</button></article>`).join('')}</section>`}
function products(){return `<section class="panel"><div class="panel-head"><div><h2>Produtos</h2><p class="muted">Foto recomendada: <b>1000 × 1000 px</b> · 1:1 · JPG/PNG/WebP.</p></div></div><div class="product-grid">${state.data.products.map(x=>`<article class="editor-card product-card">${preview(x.image_url,'1/1')}${uploadBox({table:'products',id:x.id,field:'image_url',folder:'produtos',accept:'image/*',label:'Trocar foto',spec:'1000 × 1000 px · 1:1'})}<label>Nome<input data-edit-table="products" data-id="${x.id}" data-field="name" value="${esc(x.name)}"></label><label>Preço<input type="number" step="0.01" data-edit-table="products" data-id="${x.id}" data-field="price" value="${x.price||0}"></label><label>Categoria<input data-edit-table="products" data-id="${x.id}" data-field="category" value="${esc(x.category||'')}"></label><label class="switch-line">Disponível <span class="switch"><input type="checkbox" data-auto table="products" data-id="${x.id}" data-field="is_available" ${x.is_available?'checked':''}><span></span></span></label><button class="save" data-save-table="products" data-id="${x.id}">Salvar produto</button></article>`).join('')}</div></section>`}
function orders(){return `<section class="panel"><h2>Pedidos recentes</h2><table><thead><tr><th>Cliente</th><th>Status</th><th>Total</th></tr></thead><tbody>${state.data.orders.map(x=>`<tr><td>${esc(x.customer_name||'Cliente')}</td><td>${esc(x.status)}</td><td>${money(x.total)}</td></tr>`).join('')}</tbody></table></section>`}
function events(){return `<section class="panel"><div class="panel-head"><div><h2>Eventos</h2><p class="muted">Capa recomendada: <b>1200 × 675 px</b> · 16:9.</p></div></div>${state.data.events.length?state.data.events.map(x=>`<article class="editor-card"><div class="banner-workspace">${preview(x.image_url,'16/9')}<div>${uploadBox({table:'events',id:x.id,field:'image_url',folder:'eventos',accept:'image/*',label:'Trocar capa',spec:'1200 × 675 px · 16:9'})}<div class="form-grid"><label>Título<input data-edit-table="events" data-id="${x.id}" data-field="title" value="${esc(x.title)}"></label><label>Local<input data-edit-table="events" data-id="${x.id}" data-field="location_text" value="${esc(x.location_text||'')}"></label><label>CTA<input data-edit-table="events" data-id="${x.id}" data-field="cta_label" value="${esc(x.cta_label||'')}"></label><label>Link<input data-edit-table="events" data-id="${x.id}" data-field="target_url" value="${esc(x.target_url||'')}"></label></div><button class="save" data-save-table="events" data-id="${x.id}">Salvar evento</button></div></div></article>`).join(''):`<div class="empty">Nenhum evento cadastrado. O módulo está pronto para receber o primeiro.</div>`}</section>`}
function media(){return `<section class="panel"><h2>Biblioteca de Mídia</h2><p class="muted">Envie arquivos avulsos para o bucket <b>zecapao-media</b>. O link público será copiado automaticamente.</p>${uploadBox({folder:'biblioteca',accept:'image/*,video/mp4,video/webm',label:'Adicionar mídia à biblioteca',spec:'Imagens e vídeos · até 25 MB',standalone:true})}<div class="library-result" id="libraryResult"></div></section>`}

async function uploadMedia(input){const file=input.files?.[0];if(!file)return;if(file.size>25*1024*1024){notify('Arquivo acima de 25 MB.','err');input.value='';return}const table=input.dataset.table,id=input.dataset.id,field=input.dataset.field,folder=input.dataset.folder||'geral',safe=slug(file.name),path=`${folder}/${id||'avulsos'}/${Date.now()}-${safe}`,progress=document.querySelector(`[data-progress="${table}-${id}-${field}"]`);if(progress)progress.textContent='Enviando...';const{error}=await supabase.storage.from('zecapao-media').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error){if(progress)progress.textContent='Erro no upload';notify(error.message,'err');return}const{data:{publicUrl}}=supabase.storage.from('zecapao-media').getPublicUrl(path);if(input.dataset.standalone){const r=document.querySelector('#libraryResult');if(r)r.innerHTML=`<div class="success-box"><b>Upload concluído</b><input value="${esc(publicUrl)}" readonly></div>`;try{await navigator.clipboard.writeText(publicUrl)}catch{}notify('Mídia enviada. Link copiado.');return}const payload={[field]:publicUrl,updated_at:new Date().toISOString()};if(table==='app_entry_config')payload.media_type=file.type.startsWith('video/')?'video':'image';const{error:updateError}=await supabase.from(table).update(payload).eq('id',id);if(updateError){notify(updateError.message,'err');return}notify('Mídia enviada e salva ✓');await refresh()}
async function saveEditor(btn){const table=btn.dataset.saveTable,id=btn.dataset.id,els=[...document.querySelectorAll(`[data-edit-table="${table}"][data-id="${id}"]`)],payload={updated_at:new Date().toISOString()};els.forEach(f=>payload[f.dataset.field]=f.type==='number'?Number(f.value):f.value);const{error}=await supabase.from(table).update(payload).eq('id',id);if(error)return notify(error.message,'err');notify('Alterações salvas ✓');await refresh()}
async function bindActions(){document.querySelectorAll('[data-upload]').forEach(i=>i.onchange=()=>uploadMedia(i));document.querySelectorAll('[data-save-table]').forEach(b=>b.onclick=()=>saveEditor(b));document.querySelectorAll('[data-auto]').forEach(el=>el.onchange=async()=>{const table=el.getAttribute('table'),{error}=await supabase.from(table).update({[el.dataset.field]:el.checked,updated_at:new Date().toISOString()}).eq('id',el.dataset.id);if(error)notify(error.message,'err');else notify('Status atualizado ✓')})}
async function refresh(){await loadAll();render()}function render(){if(!state.session||!state.admin)return loginView();const views={dashboard,entry,home,stores,products,orders,events,media};shell((views[state.tab]||dashboard)());bindActions()}async function boot(s){state.session=s;state.admin=await isAdmin(s);if(!state.admin){if(s)await supabase.auth.signOut();return loginView('Acesso administrativo necessário.')}await loadAll();render()}
supabase.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_OUT'){state.session=null;state.admin=false;return loginView()}if(session&&event!=='INITIAL_SESSION')await boot(session)});const{data:{session}}=await supabase.auth.getSession();if(session)await boot(session);else loginView()
