import { createClient } from '@supabase/supabase-js'
import './styles.css'

const supabase=createClient('https://yovjbqtazkreruvxoawf.supabase.co','sb_publishable_qOQlqYHbhc1005WoMOZS6g__52vXAor')
const app=document.querySelector('#app')
const state={session:null,admin:false,tab:'dashboard',data:{},storeFilter:null}
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const money=v=>`R$ ${Number(v||0).toFixed(2).replace('.',',')}`
const slugify=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')

async function isAdmin(s){if(!s?.user?.id)return false;const{data,error}=await supabase.from('profiles').select('role').eq('id',s.user.id).maybeSingle();return !error&&data?.role==='admin'}
async function loadAll(){const q=await Promise.all([
 supabase.from('app_entry_config').select('*').order('sort_order'),
 supabase.from('home_sections').select('*').order('sort_order'),
 supabase.from('stores').select('*').order('name'),
 supabase.from('products').select('*').order('sort_order'),
 supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(50),
 supabase.from('events').select('*').order('starts_at',{ascending:true}),
 supabase.from('campaign_banners').select('*').order('sort_order'),
 supabase.from('categories').select('*').order('sort_order'),
 supabase.from('profiles').select('*').order('created_at',{ascending:false})
]);['entry','home','stores','products','orders','events','banners','categories','profiles'].forEach((k,i)=>state.data[k]=q[i].data||[])}
function notify(msg,type='ok'){let n=document.querySelector('.toast');if(!n){n=document.createElement('div');n.className='toast';document.body.appendChild(n)}n.className=`toast ${type} show`;n.textContent=msg;setTimeout(()=>n.classList.remove('show'),2500)}

function loginView(message=''){app.innerHTML=`<main class="login"><section class="login-card"><div class="brand-mark">ZÉ<br><b>CAPÃO</b></div><p class="eyebrow">ADMIN v0.5</p><h1>O painel que controla o Vale.</h1><p class="muted">Acesso administrativo.</p><form id="loginForm"><label>E-mail<input name="email" type="email" required></label><label>Senha<input name="password" type="password" required></label>${message?`<div class="error">${esc(message)}</div>`:''}<button>ENTRAR</button></form></section></main>`;document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const{data,error}=await supabase.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)return loginView('E-mail ou senha inválidos.');if(!(await isAdmin(data.session))){await supabase.auth.signOut();return loginView('Conta sem permissão administrativa.')}await boot(data.session)}}

const menu=[['dashboard','Dashboard','◫'],['entry','Tela de Entrada','◉'],['home','Home','⌂'],['stores','Parceiros','◆'],['clients','Clientes','●'],['products','Cardápios','▦'],['orders','Pedidos','≡'],['events','Eventos','★'],['media','Mídias','▣']]
function shell(content){app.innerHTML=`<div class="layout"><aside><div class="logo">Zé Capão <span>ADMIN</span></div><nav>${menu.map(([id,l,i])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}"><i>${i}</i>${l}</button>`).join('')}</nav><button id="logout" class="logout">Sair</button></aside><main><header><div><p class="eyebrow">ZÉ CAPÃO ADMIN</p><h1>${menu.find(x=>x[0]===state.tab)?.[1]||''}</h1></div><div class="status">● online</div></header>${content}</main></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.storeFilter=null;render()});document.querySelector('#logout').onclick=()=>supabase.auth.signOut()}

function preview(url,ratio='2/1'){return `<div class="media-preview" style="aspect-ratio:${ratio}">${url?`<img src="${esc(url)}" alt="Prévia">`:`<div class="preview-empty"><b>SEM MÍDIA</b><small>Faça upload</small></div>`}</div>`}
function uploadBox({table,id,field,folder,spec,label}){return `<div class="upload-box"><div><b>${label}</b><small>${spec}</small></div><label class="upload-button">＋ Escolher arquivo<input hidden type="file" accept="image/jpeg,image/png,image/webp" data-upload data-table="${table}" data-id="${id}" data-field="${field}" data-folder="${folder}"></label><div class="upload-progress" data-progress="${table}-${id}-${field}"></div></div>`}
async function uploadFile(input){const file=input.files?.[0];if(!file)return;if(file.size>15*1024*1024)return notify('Arquivo maior que 15 MB','error');const key=`${input.dataset.table}-${input.dataset.id}-${input.dataset.field}`;const p=document.querySelector(`[data-progress="${key}"]`);if(p)p.textContent='Enviando…';const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-');const path=`${input.dataset.folder}/${input.dataset.id}/${Date.now()}-${safe}`;const{error:up}=await supabase.storage.from('zecapao-media').upload(path,file);if(up){if(p)p.textContent=up.message;return}const{data:{publicUrl}}=supabase.storage.from('zecapao-media').getPublicUrl(path);const payload={[input.dataset.field]:publicUrl};if(input.dataset.table!=='categories')payload.updated_at=new Date().toISOString();const{error}=await supabase.from(input.dataset.table).update(payload).eq('id',input.dataset.id);if(error){if(p)p.textContent=error.message;return}notify('Mídia publicada ✓');await refresh()}

function dashboard(){const d=state.data;return `<section class="grid stats"><article><span>Parceiros</span><b>${d.stores.length}</b></article><article><span>Clientes</span><b>${d.profiles.filter(x=>x.role!=='admin').length}</b></article><article><span>Produtos</span><b>${d.products.length}</b></article><article><span>Pedidos recentes</span><b>${d.orders.length}</b></article></section><section class="panel"><h2>Central de operação</h2><p class="muted">Conteúdo, parceiros, clientes, localização, cardápios e mídia em um só lugar.</p></section>`}

function entry(){return `<section class="panel"><h2>Tela de Entrada</h2><p class="muted"><b>1080 × 1920 px</b> · 9:16 · JPG/PNG/WebP.</p>${state.data.entry.map(x=>`<article class="editor-card"><div class="row"><div><b>${esc(x.name)}</b><small>${esc(x.mode)}</small></div></div><div class="entry-workspace">${preview(x.media_url,'9/16')}<div>${uploadBox({table:'app_entry_config',id:x.id,field:'media_url',folder:'entrada',spec:'1080 × 1920 px · 9:16',label:'Adicionar / substituir mídia'})}<div class="form-grid"><label>Título<input data-edit-table="app_entry_config" data-id="${x.id}" data-field="title" value="${esc(x.title||'')}"></label><label>Subtítulo<input data-edit-table="app_entry_config" data-id="${x.id}" data-field="subtitle" value="${esc(x.subtitle||'')}"></label><label>Modo<select data-edit-table="app_entry_config" data-id="${x.id}" data-field="mode">${['login','login_campaign','media_fullscreen','media_then_login'].map(m=>`<option ${x.mode===m?'selected':''}>${m}</option>`).join('')}</select></label><label>Duração<input type="number" data-edit-table="app_entry_config" data-id="${x.id}" data-field="media_duration_seconds" value="${x.media_duration_seconds||5}"></label></div><button class="save" data-save-table="app_entry_config" data-id="${x.id}">Salvar</button></div></div></article>`).join('')}</section>`}

function home(){return `<section class="panel"><h2>Categorias</h2><p class="muted">Ícones: <b>500 × 500 px</b> · 1:1.</p><div class="product-grid">${state.data.categories.map(c=>`<article class="editor-card">${preview((c.icon||'').startsWith('http')?c.icon:'','1/1')}${uploadBox({table:'categories',id:c.id,field:'icon',folder:'categorias',spec:'500 × 500 px · 1:1',label:esc(c.name)})}</article>`).join('')}</div><h2 class="space">Banners da Home</h2><p class="muted"><b>1200 × 600 px</b> · 2:1.</p>${state.data.banners.map(x=>`<article class="editor-card"><div class="banner-workspace">${preview(x.image_url,'2/1')}<div>${uploadBox({table:'campaign_banners',id:x.id,field:'image_url',folder:'banners',spec:'1200 × 600 px · 2:1',label:'Trocar banner'})}<div class="form-grid"><label>Título<input data-edit-table="campaign_banners" data-id="${x.id}" data-field="title" value="${esc(x.title)}"></label><label>CTA<input data-edit-table="campaign_banners" data-id="${x.id}" data-field="cta_label" value="${esc(x.cta_label||'')}"></label></div><button class="save" data-save-table="campaign_banners" data-id="${x.id}">Salvar banner</button></div></div></article>`).join('')}</section>`}

function stores(){return `<section class="panel"><div class="panel-head"><div><h2>Parceiros</h2><p class="muted">Cadastre, localize, edite, desative e abra o cardápio de cada parceiro.</p></div><button class="save" id="newStoreBtn">＋ Novo parceiro</button></div><div id="newStoreForm" class="editor-card hidden"><div class="form-grid"><label>Nome<input id="nsName"></label><label>Telefone<input id="nsPhone"></label><label>Endereço<input id="nsAddress"></label><label>Categoria<select id="nsCategory"><option value="">Sem categoria</option>${state.data.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Latitude<input id="nsLat" type="number" step="any"></label><label>Longitude<input id="nsLng" type="number" step="any"></label></div><button class="save" id="createStoreBtn">Criar parceiro</button></div>${state.data.stores.map(x=>`<article class="editor-card"><div class="row"><div><b>${esc(x.name)}</b><small>${esc(x.slug)} · ${x.is_active?'ativo':'desativado'}</small></div><label class="switch"><input type="checkbox" data-auto table="stores" data-id="${x.id}" data-field="is_active" ${x.is_active?'checked':''}><span></span></label></div><div class="dual-media"><div>${preview(x.logo_url,'1/1')}${uploadBox({table:'stores',id:x.id,field:'logo_url',folder:'parceiros/logos',spec:'800 × 800 px · 1:1',label:'Logo'})}</div><div>${preview(x.cover_url,'16/9')}${uploadBox({table:'stores',id:x.id,field:'cover_url',folder:'parceiros/capas',spec:'1200 × 675 px · 16:9',label:'Capa'})}</div></div><div class="form-grid"><label>Nome<input data-edit-table="stores" data-id="${x.id}" data-field="name" value="${esc(x.name)}"></label><label>Telefone<input data-edit-table="stores" data-id="${x.id}" data-field="phone" value="${esc(x.phone||'')}"></label><label class="wide">Endereço<input data-edit-table="stores" data-id="${x.id}" data-field="address" value="${esc(x.address||'')}"></label><label>Latitude<input type="number" step="any" data-edit-table="stores" data-id="${x.id}" data-field="latitude" value="${x.latitude??''}"></label><label>Longitude<input type="number" step="any" data-edit-table="stores" data-id="${x.id}" data-field="longitude" value="${x.longitude??''}"></label></div><div class="row"><button class="save" data-save-table="stores" data-id="${x.id}">Salvar parceiro</button><button class="secondary" data-menu-store="${x.id}">Abrir cardápio (${state.data.products.filter(p=>p.store_id===x.id).length})</button><button class="danger" data-deactivate-store="${x.id}">Excluir / desativar</button></div></article>`).join('')}</section>`}

function clients(){const clients=state.data.profiles.filter(x=>x.role!=='admin');return `<section class="panel"><div class="panel-head"><div><h2>Clientes</h2><p class="muted">Cadastro administrativo. Excluir = desativar, preservando histórico.</p></div><button class="save" id="newClientBtn">＋ Novo cliente</button></div><div id="newClientForm" class="editor-card hidden"><div class="form-grid"><label>Nome<input id="ncName"></label><label>E-mail<input id="ncEmail" type="email"></label><label>Telefone<input id="ncPhone"></label><label>Endereço<input id="ncAddress"></label><label>Latitude<input id="ncLat" type="number" step="any"></label><label>Longitude<input id="ncLng" type="number" step="any"></label></div><button class="save" id="createClientBtn">Adicionar cliente</button></div>${clients.map(x=>`<article class="editor-card"><div class="row"><div><b>${esc(x.full_name||'Cliente')}</b><small>${esc(x.email||'')} · ${x.is_active===false?'desativado':'ativo'}</small></div><label class="switch"><input type="checkbox" data-auto table="profiles" data-id="${x.id}" data-field="is_active" ${x.is_active!==false?'checked':''}><span></span></label></div><div class="form-grid"><label>Nome<input data-edit-table="profiles" data-id="${x.id}" data-field="full_name" value="${esc(x.full_name||'')}"></label><label>E-mail<input data-edit-table="profiles" data-id="${x.id}" data-field="email" value="${esc(x.email||'')}"></label><label>Telefone<input data-edit-table="profiles" data-id="${x.id}" data-field="phone" value="${esc(x.phone||'')}"></label><label>Endereço<input data-edit-table="profiles" data-id="${x.id}" data-field="address" value="${esc(x.address||'')}"></label><label>Latitude<input type="number" step="any" data-edit-table="profiles" data-id="${x.id}" data-field="latitude" value="${x.latitude??''}"></label><label>Longitude<input type="number" step="any" data-edit-table="profiles" data-id="${x.id}" data-field="longitude" value="${x.longitude??''}"></label></div><div class="row"><button class="save" data-save-table="profiles" data-id="${x.id}">Salvar cliente</button><button class="danger" data-deactivate-client="${x.id}">Excluir / desativar</button></div></article>`).join('')}</section>`}

function products(){const stores=state.data.stores;const list=state.storeFilter?state.data.products.filter(p=>p.store_id===state.storeFilter):state.data.products;return `<section class="panel"><div class="panel-head"><div><h2>Cardápios</h2><p class="muted">Produtos sempre vinculados ao parceiro correto.</p></div><select id="storeFilter"><option value="">Todos os parceiros</option>${stores.map(s=>`<option value="${s.id}" ${state.storeFilter===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="editor-card"><h3>Novo item</h3><div class="form-grid"><label>Parceiro<select id="npStore">${stores.map(s=>`<option value="${s.id}" ${state.storeFilter===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>Nome<input id="npName"></label><label>Preço<input id="npPrice" type="number" step="0.01"></label><label>Categoria<input id="npCategory"></label></div><button class="save" id="createProductBtn">Adicionar ao cardápio</button></div><div class="product-grid">${list.map(x=>`<article class="editor-card product-card">${preview(x.image_url,'1/1')}${uploadBox({table:'products',id:x.id,field:'image_url',folder:'produtos',spec:'1000 × 1000 px · 1:1',label:'Foto do item'})}<b>${esc(x.name)}</b><small>${esc(stores.find(s=>s.id===x.store_id)?.name||'')}</small><div class="form-grid"><label>Nome<input data-edit-table="products" data-id="${x.id}" data-field="name" value="${esc(x.name)}"></label><label>Preço<input type="number" step="0.01" data-edit-table="products" data-id="${x.id}" data-field="price" value="${x.price||0}"></label><label>Categoria<input data-edit-table="products" data-id="${x.id}" data-field="category" value="${esc(x.category||'')}"></label></div><button class="save" data-save-table="products" data-id="${x.id}">Salvar item</button></article>`).join('')}</div></section>`}

function orders(){return `<section class="panel"><h2>Pedidos recentes</h2><table><thead><tr><th>Cliente</th><th>Status</th><th>Total</th></tr></thead><tbody>${state.data.orders.map(x=>`<tr><td>${esc(x.customer_name||'Cliente')}</td><td>${esc(x.status||'')}</td><td>${money(x.total)}</td></tr>`).join('')}</tbody></table></section>`}
function events(){return `<section class="panel"><h2>Eventos</h2><p class="muted">Capa: <b>1200 × 675 px</b>.</p>${state.data.events.map(x=>`<article class="editor-card">${preview(x.image_url,'16/9')}${uploadBox({table:'events',id:x.id,field:'image_url',folder:'eventos',spec:'1200 × 675 px · 16:9',label:'Capa do evento'})}<b>${esc(x.title)}</b></article>`).join('')}</section>`}
function media(){return `<section class="panel"><h2>Mídias</h2><div class="drop"><b>Storage ativo ✓</b><br><small>Entrada · banners · categorias · parceiros · produtos · eventos</small></div></section>`}

async function saveRecord(table,id){const els=[...document.querySelectorAll(`[data-edit-table="${table}"][data-id="${id}"]`)];const payload={};els.forEach(f=>payload[f.dataset.field]=f.type==='number'?(f.value===''?null:Number(f.value)):f.value);if(table!=='categories')payload.updated_at=new Date().toISOString();const{error}=await supabase.from(table).update(payload).eq('id',id);if(error)notify(error.message,'error');else notify('Salvo ✓')}
async function bind(){document.querySelectorAll('[data-upload]').forEach(i=>i.onchange=()=>uploadFile(i));document.querySelectorAll('[data-save-table]').forEach(b=>b.onclick=()=>saveRecord(b.dataset.saveTable,b.dataset.id));document.querySelectorAll('[data-auto]').forEach(el=>el.onchange=async()=>{const table=el.getAttribute('table'),payload={[el.dataset.field]:el.checked};if(table!=='categories')payload.updated_at=new Date().toISOString();const{error}=await supabase.from(table).update(payload).eq('id',el.dataset.id);if(error)notify(error.message,'error')});document.querySelectorAll('[data-menu-store]').forEach(b=>b.onclick=()=>{state.storeFilter=b.dataset.menuStore;state.tab='products';render()});document.querySelectorAll('[data-deactivate-store]').forEach(b=>b.onclick=async()=>{if(!confirm('Desativar este parceiro? O histórico e o cardápio serão preservados.'))return;await supabase.from('stores').update({is_active:false,is_open:false,updated_at:new Date().toISOString()}).eq('id',b.dataset.deactivateStore);await refresh()});document.querySelectorAll('[data-deactivate-client]').forEach(b=>b.onclick=async()=>{if(!confirm('Desativar este cliente? O histórico será preservado.'))return;await supabase.from('profiles').update({is_active:false,updated_at:new Date().toISOString()}).eq('id',b.dataset.deactivateClient);await refresh()});
const ns=document.querySelector('#newStoreBtn');if(ns)ns.onclick=()=>document.querySelector('#newStoreForm').classList.toggle('hidden');const cs=document.querySelector('#createStoreBtn');if(cs)cs.onclick=async()=>{const name=document.querySelector('#nsName').value.trim();if(!name)return notify('Informe o nome','error');const{error}=await supabase.from('stores').insert({name,slug:slugify(name),phone:document.querySelector('#nsPhone').value,address:document.querySelector('#nsAddress').value,category_id:document.querySelector('#nsCategory').value||null,latitude:Number(document.querySelector('#nsLat').value)||null,longitude:Number(document.querySelector('#nsLng').value)||null,is_active:true,is_open:true});if(error)notify(error.message,'error');else{notify('Parceiro criado ✓');await refresh()}};
const nc=document.querySelector('#newClientBtn');if(nc)nc.onclick=()=>document.querySelector('#newClientForm').classList.toggle('hidden');const cc=document.querySelector('#createClientBtn');if(cc)cc.onclick=async()=>{const name=document.querySelector('#ncName').value.trim();if(!name)return notify('Informe o nome','error');const{error}=await supabase.from('profiles').insert({id:crypto.randomUUID(),full_name:name,email:document.querySelector('#ncEmail').value,phone:document.querySelector('#ncPhone').value,address:document.querySelector('#ncAddress').value,latitude:Number(document.querySelector('#ncLat').value)||null,longitude:Number(document.querySelector('#ncLng').value)||null,role:'customer',is_active:true});if(error)notify(error.message,'error');else{notify('Cliente adicionado ✓');await refresh()}};
const sf=document.querySelector('#storeFilter');if(sf)sf.onchange=()=>{state.storeFilter=sf.value||null;render()};const cp=document.querySelector('#createProductBtn');if(cp)cp.onclick=async()=>{const name=document.querySelector('#npName').value.trim();if(!name)return notify('Informe o nome do item','error');const{error}=await supabase.from('products').insert({store_id:document.querySelector('#npStore').value,name,price:Number(document.querySelector('#npPrice').value)||0,category:document.querySelector('#npCategory').value,is_available:true,sort_order:0});if(error)notify(error.message,'error');else{notify('Item adicionado ✓');await refresh()}}}

async function refresh(){await loadAll();render()}function render(){if(!state.session||!state.admin)return loginView();const views={dashboard,entry,home,stores,clients,products,orders,events,media};shell((views[state.tab]||dashboard)());bind()}async function boot(s){state.session=s;state.admin=await isAdmin(s);if(!state.admin){await supabase.auth.signOut();return loginView('Acesso administrativo necessário.')}await loadAll();render()}
supabase.auth.onAuthStateChange(async(event,s)=>{if(event==='SIGNED_OUT'){state.session=null;state.admin=false;return loginView()}if(s&&event!=='INITIAL_SESSION')await boot(s)});const{data:{session}}=await supabase.auth.getSession();if(session)await boot(session);else loginView()
