name: ze_parceiro
description: Ze Parceiro MVP - operacao e gestao do estabelecimento
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
